pim_enrich_product_edit_attribute:
    path: /{id}/{dataLocale}/{scopeCode}/edit_attribute
    defaults: { _controller: DefaultValueAkeneoInlineEditBundle:InlineEdit:applyAttributeValue }
    requirements:
        id: '[0-9a-f]+'
    methods: [GET, POST]
